# Generated by Django 6.0.7 on 2026-07-16 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('accreditation_body', models.CharField(blank=True, help_text='ex: COFRAC, ISO 15189, ISO 17025', max_length=100)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
                ('accreditation_scope', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InternalQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyte', models.CharField(help_text='Paramètre analysé', max_length=255)),
                ('control_level', models.CharField(help_text='ex: Niveau 1, 2, 3', max_length=50)),
                ('date', models.DateField()),
                ('measured_value', models.FloatField()),
                ('target_mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('is_within_limits', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.equipment')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_controls', to='quality.laboratory')),
            ],
            options={
                'verbose_name': 'Contrôle interne qualité (CIQ)',
                'verbose_name_plural': 'Contrôles internes qualité (CIQ)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalQualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Organisme fournisseur EEQ', max_length=255)),
                ('analyte', models.CharField(max_length=255)),
                ('round_reference', models.CharField(help_text='Référence de la campagne', max_length=100)),
                ('date_received', models.DateField()),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('deviation_score', models.FloatField(blank=True, help_text='Z-score ou équivalent', null=True)),
                ('is_satisfactory', models.BooleanField(default=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_assessments', to='quality.laboratory')),
            ],
            options={
                'verbose_name': 'Évaluation externe de la qualité (EEQ)',
                'verbose_name_plural': 'Évaluations externes de la qualité (EEQ)',
                'ordering': ['-date_received'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='quality.laboratory'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('under_review', 'En cours de traitement'), ('closed', 'Clôturée')], default='open', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='quality.laboratory')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('internal', 'Audit interne'), ('external', 'Audit externe / accréditation')], max_length=10)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('scope', models.TextField(help_text='Périmètre audité')),
                ('auditor', models.CharField(blank=True, max_length=255)),
                ('planned_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='planned', max_length=15)),
                ('findings', models.TextField(blank=True, help_text="Constats de l'audit")),
                ('action_plan', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='quality.laboratory')),
            ],
            options={
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('period_covered', models.CharField(help_text='ex: Année 2025', max_length=100)),
                ('summary', models.TextField()),
                ('decisions', models.TextField(blank=True)),
                ('attendees', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_reviews', to='quality.laboratory')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='ex: NC-2026-001', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phase', models.CharField(choices=[('pre', 'Pré-analytique'), ('analytical', 'Analytique'), ('post', 'Post-analytique')], max_length=15)),
                ('severity', models.CharField(choices=[('low', 'Mineure'), ('medium', 'Majeure'), ('high', 'Critique')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('investigating', 'Analyse des causes en cours'), ('action_planned', "Plan d'action défini"), ('closed', 'Clôturée')], default='open', max_length=20)),
                ('root_cause_analysis', models.TextField(blank=True, help_text='Analyse des causes (5M, Ishikawa, 5 Pourquoi...)')),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('detected_at', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_non_conformities', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='quality.laboratory')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_non_conformities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'non conformities',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tat', 'Délai de rendu des résultats'), ('error_rate', "Taux d'erreurs"), ('rejection', "Taux de rejet d'échantillons"), ('satisfaction', 'Satisfaction client/patient'), ('other', 'Autre')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_value', models.FloatField(help_text='Objectif à atteindre')),
                ('actual_value', models.FloatField(help_text='Valeur mesurée')),
                ('unit', models.CharField(blank=True, help_text='%, jours, heures...', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='quality.laboratory')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('training_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_qualified', models.BooleanField(default=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training_certificates/%Y/%m/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='quality.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('procedure', 'Procédure'), ('sop', 'Mode opératoire (SOP)'), ('policy', 'Politique qualité'), ('form', 'Formulaire / enregistrement'), ('manual', 'Manuel qualité')], max_length=15)),
                ('reference', models.CharField(help_text='ex: PROC-QUAL-012', max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='quality_documents/%Y/%m/')),
                ('is_validated', models.BooleanField(default=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quality.laboratory')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reference'],
                'unique_together': {('laboratory', 'reference', 'version')},
            },
        ),
    ]
